// Minimal — generated by @web-kits/audio (do not edit)
// patch: Minimal
import type { SoundDefinition, SoundPatch } from "@web-kits/audio";

export const tap: SoundDefinition = {"source":{"type":"sine","frequency":1200},"envelope":{"attack":0,"decay":0.012,"sustain":0,"release":0.004},"gain":0.08};
export const click: SoundDefinition = {"source":{"type":"sine","frequency":800},"envelope":{"attack":0,"decay":0.015,"sustain":0,"release":0.005},"gain":0.1};
export const keyPress: SoundDefinition = {"source":{"type":"sine","frequency":1100},"envelope":{"attack":0,"decay":0.01,"sustain":0,"release":0.003},"gain":0.06};
export const toggleOn: SoundDefinition = {"layers":[{"source":{"type":"sine","frequency":880},"envelope":{"attack":0,"decay":0.02,"sustain":0,"release":0.006},"gain":0.08},{"source":{"type":"sine","frequency":1320},"envelope":{"attack":0,"decay":0.02,"sustain":0,"release":0.006},"delay":0.03,"gain":0.07}]};
export const toggleOff: SoundDefinition = {"layers":[{"source":{"type":"sine","frequency":1320},"envelope":{"attack":0,"decay":0.02,"sustain":0,"release":0.006},"gain":0.08},{"source":{"type":"sine","frequency":880},"envelope":{"attack":0,"decay":0.02,"sustain":0,"release":0.006},"delay":0.03,"gain":0.07}]};
export const checkbox: SoundDefinition = {"source":{"type":"sine","frequency":1000},"envelope":{"attack":0,"decay":0.018,"sustain":0,"release":0.005},"gain":0.09};
export const select: SoundDefinition = {"source":{"type":"sine","frequency":1100},"envelope":{"attack":0,"decay":0.02,"sustain":0,"release":0.006},"gain":0.08};
export const deselect: SoundDefinition = {"source":{"type":"sine","frequency":900},"envelope":{"attack":0,"decay":0.018,"sustain":0,"release":0.005},"gain":0.06};
export const hover: SoundDefinition = {"source":{"type":"sine","frequency":1300},"envelope":{"attack":0,"decay":0.01,"sustain":0,"release":0.004},"gain":0.04};
export const tabSwitch: SoundDefinition = {"source":{"type":"sine","frequency":1050},"envelope":{"attack":0,"decay":0.015,"sustain":0,"release":0.005},"gain":0.07};
export const expand: SoundDefinition = {"source":{"type":"sine","frequency":{"start":800,"end":1000}},"envelope":{"attack":0,"decay":0.04,"sustain":0,"release":0.012},"gain":0.06};
export const collapse: SoundDefinition = {"source":{"type":"sine","frequency":{"start":1000,"end":800}},"envelope":{"attack":0,"decay":0.04,"sustain":0,"release":0.012},"gain":0.06};
export const pageEnter: SoundDefinition = {"source":{"type":"sine","frequency":{"start":700,"end":900}},"envelope":{"attack":0.003,"decay":0.04,"sustain":0,"release":0.015},"gain":0.05};
export const pageExit: SoundDefinition = {"source":{"type":"sine","frequency":{"start":900,"end":700}},"envelope":{"attack":0,"decay":0.04,"sustain":0,"release":0.015},"gain":0.04};
export const success: SoundDefinition = {"layers":[{"source":{"type":"sine","frequency":523},"envelope":{"attack":0,"decay":0.05,"sustain":0,"release":0.015},"gain":0.1},{"source":{"type":"sine","frequency":784},"envelope":{"attack":0,"decay":0.05,"sustain":0,"release":0.015},"delay":0.06,"gain":0.08}]};
export const error: SoundDefinition = {"layers":[{"source":{"type":"sine","frequency":300},"envelope":{"attack":0,"decay":0.04,"sustain":0,"release":0.012},"gain":0.12},{"source":{"type":"sine","frequency":280},"envelope":{"attack":0,"decay":0.04,"sustain":0,"release":0.012},"delay":0.01,"gain":0.1}]};
export const warning: SoundDefinition = {"layers":[{"source":{"type":"sine","frequency":440},"envelope":{"attack":0,"decay":0.03,"sustain":0,"release":0.01},"gain":0.1},{"source":{"type":"sine","frequency":466},"envelope":{"attack":0,"decay":0.03,"sustain":0,"release":0.01},"delay":0.008,"gain":0.08}]};
export const notification: SoundDefinition = {"layers":[{"source":{"type":"sine","frequency":660},"envelope":{"attack":0,"decay":0.05,"sustain":0,"release":0.02},"gain":0.1},{"source":{"type":"sine","frequency":880},"envelope":{"attack":0,"decay":0.04,"sustain":0,"release":0.015},"delay":0.08,"gain":0.08}]};
export const info: SoundDefinition = {"source":{"type":"sine","frequency":880},"envelope":{"attack":0,"decay":0.04,"sustain":0,"release":0.015},"gain":0.08};
export const copy: SoundDefinition = {"layers":[{"source":{"type":"sine","frequency":1000},"envelope":{"attack":0,"decay":0.012,"sustain":0,"release":0.004},"gain":0.08},{"source":{"type":"sine","frequency":1200},"envelope":{"attack":0,"decay":0.012,"sustain":0,"release":0.004},"delay":0.035,"gain":0.07}]};
export const send: SoundDefinition = {"source":{"type":"sine","frequency":{"start":600,"end":1000}},"envelope":{"attack":0,"decay":0.04,"sustain":0,"release":0.012},"gain":0.08};
export const _delete: SoundDefinition = {"source":{"type":"sine","frequency":{"start":500,"end":250}},"envelope":{"attack":0,"decay":0.05,"sustain":0,"release":0.015},"gain":0.1};
export const undo: SoundDefinition = {"source":{"type":"sine","frequency":{"start":800,"end":600}},"envelope":{"attack":0,"decay":0.035,"sustain":0,"release":0.01},"gain":0.07};
export const pop: SoundDefinition = {"source":{"type":"sine","frequency":{"start":400,"end":200}},"envelope":{"attack":0,"decay":0.04,"sustain":0,"release":0.012},"gain":0.1};
export const swoosh: SoundDefinition = {"source":{"type":"sine","frequency":{"start":600,"end":1400}},"envelope":{"attack":0.005,"decay":0.04,"sustain":0,"release":0.015},"gain":0.05};
export const slide: SoundDefinition = {"source":{"type":"sine","frequency":{"start":800,"end":1100}},"envelope":{"attack":0.003,"decay":0.035,"sustain":0,"release":0.012},"gain":0.05};

export const _patch: SoundPatch = {
  ...{"name":"Minimal","author":"Raphael Salaja","version":"1.0.0","description":"An ultra-clean sine-based palette for quiet, transparent UI feedback, made for products that prioritize subtlety, restraint, and smooth interaction cues over expressive flourish."},
  sounds: { tap, click, "key-press": keyPress, "toggle-on": toggleOn, "toggle-off": toggleOff, checkbox, select, deselect, hover, "tab-switch": tabSwitch, expand, collapse, "page-enter": pageEnter, "page-exit": pageExit, success, error, warning, notification, info, copy, send, "delete": _delete, undo, pop, swoosh, slide },
};
